subdir-ccflags-y := \
    -fdata-sections -ffunction-sections -finline-functions -ftree-vectorize -funroll-loops

obj-$(CONFIG_COMMON_FP)	+= common/
obj-$(CONFIG_CDFINGER_FP)	+= cdfingerfp/
obj-$(CONFIG_GOODIX_FP)	+= goodixfp/
