
name: Build Kernel
on:
  push:
    branches:
      - sdm660-test
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Building Kernel
      run: ./build.sh
