
name: Build Kernel Test
on:
  push:
    branches:
      - sdm660-eas-test
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get -y install bc build-essential bison flex zip gcc clang libc6 curl libstdc++6 git wget libssl-dev zstd openjdk-11-jdk openjdk-11-jre python
    - name: Build Asus Zenfone Max Pro M1
      run: ./X00TD.sh
    - name: Build Asus Zenfone Max Pro M2
      run: ./X01BD.sh
